# fly.toml app configuration file generated for kannape-go on 2025-09-28T20:53:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kannape-go'
primary_region = 'cdg'

[build] 
dockerfile = "Dockerfile" # uses dockerfile

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
